# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_query_widget.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_QueryForm(object):
    def setupUi(self, QueryForm):
        QueryForm.setObjectName("QueryForm")
        QueryForm.resize(868, 706)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(QueryForm)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.splitter = QtWidgets.QSplitter(QueryForm)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.query_view = QtWidgets.QWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(4)
        sizePolicy.setHeightForWidth(self.query_view.sizePolicy().hasHeightForWidth())
        self.query_view.setSizePolicy(sizePolicy)
        self.query_view.setObjectName("query_view")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.query_view)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(4)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.layout_line1 = QtWidgets.QHBoxLayout()
        self.layout_line1.setContentsMargins(10, -1, -1, -1)
        self.layout_line1.setObjectName("layout_line1")
        self.ico_host = QtWidgets.QLabel(self.query_view)
        self.ico_host.setText("")
        self.ico_host.setPixmap(QtGui.QPixmap(":/resources/icon/computer_link.png"))
        self.ico_host.setObjectName("ico_host")
        self.layout_line1.addWidget(self.ico_host)
        self.label_host = QtWidgets.QLabel(self.query_view)
        self.label_host.setObjectName("label_host")
        self.layout_line1.addWidget(self.label_host)
        self.ico_index = QtWidgets.QLabel(self.query_view)
        self.ico_index.setText("")
        self.ico_index.setPixmap(QtGui.QPixmap(":/resources/icon/wrap_off.png"))
        self.ico_index.setObjectName("ico_index")
        self.layout_line1.addWidget(self.ico_index)
        self.label_index = QtWidgets.QLabel(self.query_view)
        self.label_index.setObjectName("label_index")
        self.layout_line1.addWidget(self.label_index)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layout_line1.addItem(spacerItem)
        self.verticalLayout_8.addLayout(self.layout_line1)
        self.layout_line2 = QtWidgets.QHBoxLayout()
        self.layout_line2.setContentsMargins(-1, -1, -1, 0)
        self.layout_line2.setObjectName("layout_line2")
        self.combo_index = QtWidgets.QComboBox(self.query_view)
        self.combo_index.setObjectName("combo_index")
        self.layout_line2.addWidget(self.combo_index)
        self.btn_query = QtWidgets.QPushButton(self.query_view)
        self.btn_query.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/resources/icon/execute.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_query.setIcon(icon)
        self.btn_query.setObjectName("btn_query")
        self.layout_line2.addWidget(self.btn_query)
        self.pushButton_4 = QtWidgets.QPushButton(self.query_view)
        self.pushButton_4.setEnabled(False)
        self.pushButton_4.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/resources/icon/execute_selection_gt.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon1)
        self.pushButton_4.setObjectName("pushButton_4")
        self.layout_line2.addWidget(self.pushButton_4)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layout_line2.addItem(spacerItem1)
        self.verticalLayout_8.addLayout(self.layout_line2)
        self.tabWidget = QtWidgets.QTabWidget(self.query_view)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_comp = QtWidgets.QWidget()
        self.tab_comp.setObjectName("tab_comp")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab_comp)
        self.verticalLayout.setObjectName("verticalLayout")
        self.text_query = QtWidgets.QPlainTextEdit(self.tab_comp)
        self.text_query.setObjectName("text_query")
        self.verticalLayout.addWidget(self.text_query)
        self.tabWidget.addTab(self.tab_comp, "")
        self.tab_simple = QtWidgets.QWidget()
        self.tab_simple.setEnabled(True)
        self.tab_simple.setObjectName("tab_simple")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.tab_simple)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.groupBox = QtWidgets.QGroupBox(self.tab_simple)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(14)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.scrollArea = QtWidgets.QScrollArea(self.groupBox)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.field_group = QtWidgets.QWidget()
        self.field_group.setGeometry(QtCore.QRect(0, 0, 506, 99))
        self.field_group.setObjectName("field_group")
        self.field_group_layout = QtWidgets.QVBoxLayout(self.field_group)
        self.field_group_layout.setContentsMargins(0, 0, 0, 0)
        self.field_group_layout.setObjectName("field_group_layout")
        self.field_query_line = QtWidgets.QHBoxLayout()
        self.field_query_line.setObjectName("field_query_line")
        self.comboBox = QtWidgets.QComboBox(self.field_group)
        self.comboBox.setMaximumSize(QtCore.QSize(100, 16777215))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.field_query_line.addWidget(self.comboBox, 0, QtCore.Qt.AlignTop)
        self.comboBox_2 = QtWidgets.QComboBox(self.field_group)
        self.comboBox_2.setObjectName("comboBox_2")
        self.field_query_line.addWidget(self.comboBox_2, 0, QtCore.Qt.AlignTop)
        self.pushButton_5 = QtWidgets.QPushButton(self.field_group)
        self.pushButton_5.setMaximumSize(QtCore.QSize(20, 16777215))
        self.pushButton_5.setObjectName("pushButton_5")
        self.field_query_line.addWidget(self.pushButton_5, 0, QtCore.Qt.AlignTop)
        self.pushButton_6 = QtWidgets.QPushButton(self.field_group)
        self.pushButton_6.setMaximumSize(QtCore.QSize(20, 16777215))
        self.pushButton_6.setObjectName("pushButton_6")
        self.field_query_line.addWidget(self.pushButton_6, 0, QtCore.Qt.AlignTop)
        self.field_group_layout.addLayout(self.field_query_line)
        self.scrollArea.setWidget(self.field_group)
        self.verticalLayout_3.addWidget(self.scrollArea)
        self.horizontalLayout_7.addWidget(self.groupBox)
        self.group_other = QtWidgets.QGroupBox(self.tab_simple)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(6)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.group_other.sizePolicy().hasHeightForWidth())
        self.group_other.setSizePolicy(sizePolicy)
        self.group_other.setObjectName("group_other")
        self.formLayout = QtWidgets.QFormLayout(self.group_other)
        self.formLayout.setHorizontalSpacing(3)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.group_other)
        self.label.setMaximumSize(QtCore.QSize(70, 16777215))
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_2 = QtWidgets.QLabel(self.group_other)
        self.label_2.setMaximumSize(QtCore.QSize(70, 16777215))
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.combo_include = QtWidgets.QComboBox(self.group_other)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combo_include.sizePolicy().hasHeightForWidth())
        self.combo_include.setSizePolicy(sizePolicy)
        self.combo_include.setObjectName("combo_include")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.combo_include)
        self.combo_exculde = QtWidgets.QComboBox(self.group_other)
        self.combo_exculde.setObjectName("combo_exculde")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.combo_exculde)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.combo_sort_type = QtWidgets.QComboBox(self.group_other)
        self.combo_sort_type.setMinimumSize(QtCore.QSize(70, 0))
        self.combo_sort_type.setMaximumSize(QtCore.QSize(60, 16777215))
        self.combo_sort_type.setObjectName("combo_sort_type")
        self.combo_sort_type.addItem("")
        self.combo_sort_type.addItem("")
        self.horizontalLayout_6.addWidget(self.combo_sort_type)
        self.combo_sort = QtWidgets.QComboBox(self.group_other)
        self.combo_sort.setObjectName("combo_sort")
        self.horizontalLayout_6.addWidget(self.combo_sort)
        self.formLayout.setLayout(5, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_6)
        self.label_4 = QtWidgets.QLabel(self.group_other)
        self.label_4.setMaximumSize(QtCore.QSize(70, 16777215))
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.horizontalLayout_7.addWidget(self.group_other, 0, QtCore.Qt.AlignRight)
        self.tabWidget.addTab(self.tab_simple, "")
        self.verticalLayout_8.addWidget(self.tabWidget)
        self.result_view = QtWidgets.QWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(16)
        sizePolicy.setHeightForWidth(self.result_view.sizePolicy().hasHeightForWidth())
        self.result_view.setSizePolicy(sizePolicy)
        self.result_view.setObjectName("result_view")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.result_view)
        self.verticalLayout_4.setContentsMargins(10, 0, 0, 0)
        self.verticalLayout_4.setSpacing(16)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.result_view)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.btn_lock = QtWidgets.QPushButton(self.result_view)
        self.btn_lock.setEnabled(False)
        self.btn_lock.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/resources/icon/unlocked.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_lock.setIcon(icon2)
        self.btn_lock.setObjectName("btn_lock")
        self.horizontalLayout_2.addWidget(self.btn_lock)
        self.btn_ignore_null = QtWidgets.QPushButton(self.result_view)
        self.btn_ignore_null.setMaximumSize(QtCore.QSize(50, 16777215))
        self.btn_ignore_null.setCheckable(True)
        self.btn_ignore_null.setObjectName("btn_ignore_null")
        self.horizontalLayout_2.addWidget(self.btn_ignore_null)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.btn_pre_page = QtWidgets.QPushButton(self.result_view)
        self.btn_pre_page.setMaximumSize(QtCore.QSize(50, 16777215))
        self.btn_pre_page.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/resources/icon/arrow_left_tz.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_pre_page.setIcon(icon3)
        self.btn_pre_page.setObjectName("btn_pre_page")
        self.horizontalLayout_2.addWidget(self.btn_pre_page)
        self.txt_page = QtWidgets.QLineEdit(self.result_view)
        self.txt_page.setMaximumSize(QtCore.QSize(50, 16777215))
        self.txt_page.setObjectName("txt_page")
        self.horizontalLayout_2.addWidget(self.txt_page)
        self.btn_next_page = QtWidgets.QPushButton(self.result_view)
        self.btn_next_page.setMaximumSize(QtCore.QSize(50, 16777215))
        self.btn_next_page.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/resources/icon/arrow_right_tz.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_next_page.setIcon(icon4)
        self.btn_next_page.setObjectName("btn_next_page")
        self.horizontalLayout_2.addWidget(self.btn_next_page)
        self.txt_size = QtWidgets.QLineEdit(self.result_view)
        self.txt_size.setMaximumSize(QtCore.QSize(50, 16777215))
        self.txt_size.setObjectName("txt_size")
        self.horizontalLayout_2.addWidget(self.txt_size)
        self.page_info = QtWidgets.QLabel(self.result_view)
        self.page_info.setObjectName("page_info")
        self.horizontalLayout_2.addWidget(self.page_info)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.widget_4 = QtWidgets.QWidget(self.result_view)
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.tabs_result = QtWidgets.QTabWidget(self.widget_4)
        self.tabs_result.setObjectName("tabs_result")
        self.tab_table = QtWidgets.QWidget()
        self.tab_table.setObjectName("tab_table")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab_table)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.table_result = QtWidgets.QTableWidget(self.tab_table)
        self.table_result.setEditTriggers(QtWidgets.QAbstractItemView.AnyKeyPressed|QtWidgets.QAbstractItemView.EditKeyPressed)
        self.table_result.setObjectName("table_result")
        self.table_result.setColumnCount(0)
        self.table_result.setRowCount(0)
        self.verticalLayout_6.addWidget(self.table_result)
        self.tabs_result.addTab(self.tab_table, "")
        self.tab_tree = QtWidgets.QWidget()
        self.tab_tree.setObjectName("tab_tree")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.tab_tree)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.tree_result = QtWidgets.QTreeWidget(self.tab_tree)
        self.tree_result.setWordWrap(True)
        self.tree_result.setObjectName("tree_result")
        self.tree_result.headerItem().setText(0, "Key")
        self.tree_result.header().setCascadingSectionResizes(True)
        self.tree_result.header().setDefaultSectionSize(300)
        self.tree_result.header().setHighlightSections(True)
        self.tree_result.header().setMinimumSectionSize(50)
        self.tree_result.header().setStretchLastSection(True)
        self.verticalLayout_7.addWidget(self.tree_result)
        self.tabs_result.addTab(self.tab_tree, "")
        self.tab_json = QtWidgets.QWidget()
        self.tab_json.setObjectName("tab_json")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.tab_json)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.json_result = QtWidgets.QTextBrowser(self.tab_json)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.json_result.setFont(font)
        self.json_result.setObjectName("json_result")
        self.verticalLayout_10.addWidget(self.json_result)
        self.tabs_result.addTab(self.tab_json, "")
        self.verticalLayout_5.addWidget(self.tabs_result)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(0, 0, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_5 = QtWidgets.QLabel(self.widget_4)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.label_total = QtWidgets.QLabel(self.widget_4)
        self.label_total.setObjectName("label_total")
        self.horizontalLayout.addWidget(self.label_total)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.verticalLayout_4.addWidget(self.widget_4)
        self.verticalLayout_9.addWidget(self.splitter)

        self.retranslateUi(QueryForm)
        self.tabWidget.setCurrentIndex(1)
        self.tabs_result.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(QueryForm)

    def retranslateUi(self, QueryForm):
        _translate = QtCore.QCoreApplication.translate
        QueryForm.setWindowTitle(_translate("QueryForm", "Form"))
        self.label_host.setText(_translate("QueryForm", "TextLabel"))
        self.label_index.setText(_translate("QueryForm", "TextLabel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_comp), _translate("QueryForm", "Complex"))
        self.groupBox.setTitle(_translate("QueryForm", "Query"))
        self.comboBox.setItemText(0, _translate("QueryForm", "must"))
        self.comboBox.setItemText(1, _translate("QueryForm", "must_not"))
        self.comboBox.setItemText(2, _translate("QueryForm", "should"))
        self.pushButton_5.setText(_translate("QueryForm", "+"))
        self.pushButton_6.setText(_translate("QueryForm", "-"))
        self.group_other.setTitle(_translate("QueryForm", "Source"))
        self.label.setText(_translate("QueryForm", "Include:"))
        self.label_2.setText(_translate("QueryForm", "Exculde:"))
        self.combo_sort_type.setItemText(0, _translate("QueryForm", "asc"))
        self.combo_sort_type.setItemText(1, _translate("QueryForm", "desc"))
        self.label_4.setText(_translate("QueryForm", "Sort:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_simple), _translate("QueryForm", "Basic"))
        self.label_3.setText(_translate("QueryForm", "TextLabel"))
        self.btn_ignore_null.setText(_translate("QueryForm", "None"))
        self.txt_page.setText(_translate("QueryForm", "1"))
        self.txt_size.setText(_translate("QueryForm", "10"))
        self.page_info.setText(_translate("QueryForm", "Documents 1 of 1"))
        self.tabs_result.setTabText(self.tabs_result.indexOf(self.tab_table), _translate("QueryForm", "Table"))
        self.tree_result.setSortingEnabled(True)
        self.tree_result.headerItem().setText(1, _translate("QueryForm", "Value"))
        self.tree_result.headerItem().setText(2, _translate("QueryForm", "Type"))
        self.tabs_result.setTabText(self.tabs_result.indexOf(self.tab_tree), _translate("QueryForm", "Tree"))
        self.tabs_result.setTabText(self.tabs_result.indexOf(self.tab_json), _translate("QueryForm", "JSON"))
        self.label_5.setText(_translate("QueryForm", "Total: "))
        self.label_total.setText(_translate("QueryForm", "0"))
from ui import icon_rc
